using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace exerciseTwo
{
    /// <summary>
    /// Interaction logic for MainWindow.xaml
    /// </summary>
    public partial class MainWindow : Window
    {
        AdventureLiteEntities db = new AdventureLiteEntities();
        public MainWindow()
        {
            InitializeComponent();
        }

        private void lbxCustomers_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            string customer = lbxCustomers.SelectedItem as string;

            if (customer != null)
            {
                //the first query uses inheritance to change the way the information is displayed and creates a completely 
                //new object called OrderSummary which has a ToString() method attached it

                //var query = from o in db.SalesOrderHeaders
                //            where o.Customer.CompanyName.Equals(customer)
                //            select new OrderSummary
                //            {
                //                salesOrderID = o.SalesOrderID,
                //                OrderDate = o.OrderDate,
                //                TotalDue = o.TotalDue
                //            };

                //this query makes use of a partial class that is stored in a seperate folder which just adds a ToString() method in the class.
                //Essentially, you can either edit a class by editing it's properties in a partial class folder (this is important that it 
                //is done in a partial class, as if you do it in the autogenerated class properties it will cause issues, 
                //the system warns against tampering with the autogenerated code). This partial class has a ToString() method in it
                //when using a partial class in a folder, don't forget to remove the folder path from the NameSpace (".PartialClasses")

                var query = from o in db.SalesOrderHeaders
                            where o.Customer.CompanyName.Equals(customer)
                            select o;

                lbxOrders.ItemsSource = query.ToList();
            }
        }//end of bxCustomers_SelectionChanged

        private void lbxOrders_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            int orderID = Convert.ToInt32(lbxOrders.SelectedValue);

            if (orderID > 0)
            {
                var query = from od in db.SalesOrderDetails
                            where od.SalesOrderDetailID == orderID
                            select new
                            {
                                ProductName = od.Product.Name,
                                od.UnitPrice,
                                od.UnitPriceDiscount,
                                od.OrderQty,
                                od.LineTotal
                            };

                dgOrderDetails.ItemsSource = query.ToList();

            }
        }//end of lbxOrders_SelectionChanged

        private void Window_Loaded(object sender, RoutedEventArgs e)
        {
            var query = from o in db.SalesOrderHeaders
                        orderby o.Customer.CompanyName
                        select o.Customer.CompanyName;

            var result = query.ToList();

            lbxCustomers.ItemsSource = query.ToList().Distinct();

        }// end of window loaded

        public class OrderSummary : SalesOrderHeader
        {
            public override string ToString()
            {
                return string.Format("{0}:{1} {2:C}",
                    OrderDate.ToShortDateString(), SalesOrderID, TotalDue);
            }//end of partial class
        }
    }
}
